os: linux
dist: bionic
language: c
compiler: gcc

before_script:
  - pip3 install meson

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build
      - libdrm-dev
      - libgbm-dev
      - libepoxy-dev
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libcairo2-dev
      - libpixman-1-dev
      - libsystemd-dev
      - libgtk-3-dev
      - libxcb-randr0-dev
      - libudev-dev
      - libinput-dev

script:
  - mkdir build-travis
  - meson build-travis
  - ninja -C build-travis
